## cluster parameters
cluster_cmd: 'sbatch --ntasks-per-node=1 -c {threads} -J {rule}.snakemake --mem={cluster.memory} --time=24:00:00 -o {cluster.cluster_logDir}/{rule}.%j.out -e {cluster.cluster_logDir}/{rule}.%j.err'
#'qsub -V -cwd -j y -pe threaded {threads} -l h_vmem={cluster.memory},h_rt=24:00:00 -l tmpspace=100G -N {rule}.snakemake -S /bin/bash'
latency_wait: 60
__default__:
    cluster_logDir: cluster_logs
    memory: 20G
transcript_map:
    memory: 40G
velocity_map:
    memory: 40G
transcript_index:
    memory: 80G
velocity_index:
    memory: 100G
get_tcc:
    memory: 40G
get_geneCounts:
    memory: 40G
