## cluster parameters
cluster_cmd: 'qsub -cwd -j y -pe threaded {threads} -l h_vmem={cluster.memory},h_rt=24:00:00 -N {rule}.snakemake -S /bin/bash'
latency_wait: 300
cluster_logDir: cluster_logs
__default__:
    memory: 10G
transcript_index:
    memory: 30G
velocity_index:
    memory: 30G
get_tcc:
    memory: 30G
get_geneCounts:
    memory: 30G
