package:
  name: "scriapipe"
  version: "0.2"

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - snakemake >=5.11.0
    - pyyaml >=5.1
    - coreutils

test:
  commands:
    - scRIA --help

about:
  home: 'https://github.com/vivekbhr/scRIApipe'
  licence: MIT
  summary: A workflow for identifying differantial transcript usage
  licence_file: LICENSE
