## workflow parameters
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ["_R1", "_R2"])
reads: ["_R1","_R2"]
## downsample fastq to the given number before alignment
downsample:
## Trim the reads? (must-do for raw VASA-seq)
trim: False
## options for cutadapt
trimmerOptions: "-A W{'10'}"
## UCSC ID of the genome (used to fetch tx sequences)
genome_id: 'mm10'
## TSV of the barcodes (tsv file with col1 = some id, and col2 = barcode sequence)
barcode_tsv: '/hpc/hub_oudenaarden/vbhardwaj/annotations/cell_barcodes_inhouse/celseq2.bc'
## GTF file (most important, better filter for pseudogenes etc first)
input_gtf: '/hpc/hub_oudenaarden/tmakaske/projects/test/ash2l_level1-2.gtf'
## a GENCODE formatted fasta file for transcripts, this file is used to get the gene symbols etc
#cdna_fasta: 'Mus_musculus.GRCm38.cdna.all.fa'
## protocol name
protocol:
## read length (for kallisto index)
read_length:
