## workflow parameters
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ["_R1", "_R2"])
reads: ["_R1","_R2"]
## downsample fastq to the given number before alignment
downsample:
## Trim the reads?
trim: False
## options for cutadapt
trimmerOptions: "-A W{'10'}"
## UCSC ID of the genome (used to fetch tx sequences)
genome_id: 'mm10'
## TSV of the barcodes (tsv file with col1 = some id, and col2 = barcode sequence)
barcode_tsv:
## GTF file (most important, better filter for pseudogenes etc first)
input_gtf: 
## protocol name
protocol:
## read length (for kallisto index)
read_length:
